#include<iostream.h>
#include<conio.h>
#include<stdlib.h>
void main()
{
	clrscr();
	textcolor(14);
	cout<<"\n\n\n\n\n\n\t";
	cprintf("***** *   * ***** ***** *     ***** *****");
	cout<<"\n\t";
	cprintf("*     *   * *   * *   * *       *   *");
	cout<<"\n\t";
	cprintf("*     ***** ***** ***** *       *   *****");
	cout<<"\n\t";
	cprintf("*     *   * *   * * *   *       *   *");
	cout<<"\n\t";
	cprintf("***** *   * *   * *  ** ***** ***** *****");
	cout<<"\n";
	cout<<"\n\t\t\t";
	cprintf("***** *   * ***** ***** *     ***** *****");
	cout<<"\n\t\t\t";
	cprintf("*     *   * *   * *   * *       *   *");
	cout<<"\n\t\t\t";
	cprintf("*     ***** ***** ***** *       *   *****");
	cout<<"\n\t\t\t";
	cprintf("*     *   * *   * * *   *       *   *");
	cout<<"\n\t\t\t";
	cprintf("***** *   * *   * *  ** ***** ***** *****");
	cout<<"\n";
	textcolor(7);
	getch();
}