#include<iostream.h>
#include<stdio.h>
#include<stdlib.h>
#include<dos.h>
#include<conio.h>
void main()
{
	clrscr();
	textcolor(10);
	cout<<"\n\n\t\t";
	cprintf("*****  *****  *   *  *****    *****  *   *  *****");
	cout<<"\n";
	cout<<"\t\t";
	cprintf("*        *    *   *   *   *   *      **  *    *");
	cout<<"\n";
	cout<<"\t\t";
	cprintf("*****    *    *   *   *    *  ***    * * *    *");
	cout<<"\n";
	cout<<"\t\t";
	cprintf("    *    *    *   *   *   *   *      *  **    *");
	cout<<"\n";
	cout<<"\t\t";
	cprintf("*****    *    *****  *****    *****  *   *    *");
	cout<<"\n\n\n";
	cout<<"\t";
	textcolor(14);
	cprintf("*****  *****  *****  *****  *****  *****   ****    *    *****  *****");
	cout<<"\n";
	cout<<"\t";
	cprintf("*   *  *      *   *  *   *  *   *    *    *       * *   *   *   *   *");
	cout<<"\n";
	cout<<"\t";
	cprintf("*****  ***    *****  *   *  *****    *    *      *****  *****   *    *");
	cout<<"\n";
	cout<<"\t";
	cprintf("* *    *      *      *   *  * *      *    *      *   *  * *     *   *");
	cout<<"\n";
	cout<<"\t";
	cprintf("*  **  *****  *      *****  *  **    *     ****  *   *  *  **  *****");
	cout<<"\n";
	textcolor(4);
	cout<<"\n\n\t\t\t\t\t\t\t";
	cprintf("Done by,");
	cout<<"\n\t\t\t\t\t\t\t      ";
	cprintf("-B.SREERAM");
	cout<<"\n\t\t\t\t\t\t\t      ";
	cprintf("-MANISH KANCHAN");
	textcolor(7);
	getch();
}