#include<iostream.h>
#include<conio.h>
void main()
{
	clrscr();
	int a, b;
	cout<<"Enter any 2 Intigers \n";
	cin>>a;
	cin>>b;
	{
		if (a>b)
		cout<<"First value is grater than second value\n";
		else if (b>a)
		cout<<"Second value is grater than first value \n";
		else
		cout<<"First value and second value are equal \n";
	}
	for(int i=0; i<=5; i++)
	{
		cout<<"hello \t";
	}
	{
		for(int i=0; i<=5; i++)
		cout<<"\n sreeram";
	}
	getch();
}
